version: '3.3'

services:
  my_home:
    build: ./
    command: ./my_home/main
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=test
      - DB_USER=user
      - DB_PASSWORD=1234

  db:
    container_name: my_home-db
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "my_home"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5436:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

